site_name: ZarrCompatibility Documentation
site_description: Universal JSON Serialization for Python Objects

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light-blue
  features:
    - content.code.copy
    - content.code.select

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Reference: api.md
  - Examples: examples.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy  # Statt google
            docstring_section_style: spacy  # Bessere Listen-Formatierung
            show_root_heading: true
            show_root_docstring: true
            show_source: false
            members_order: source
            group_by_category: true
            show_category_heading: true
            merge_init_into_class: true
            separate_signature: true