site_name: zarrcompatibility
site_description: Universal JSON Serialization for Python Objects with Zarr Compatibility
site_url: https://fherb2.github.io/zarrcompatibility/
repo_url: https://github.com/fherb2/zarrcompatibility
repo_name: fherb2/zarrcompatibility

theme:
  name: readthedocs  # Wechsel zu readthedocs - funktioniert zuverlässig

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true

nav:
  - Home: index.md
  - User Guide: user_guide.md
  - API Reference: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_root_heading: true
            show_root_docstring: true
            show_source: false
            members_order: source
            group_by_category: true
            show_category_heading: true
            merge_init_into_class: true
            separate_signature: true
            